### ISSUE TITLE
Review Ticket Week 2

### ISSUE THREAD

**Issue by wrachel** [wrachel/TaxEvaders#14]
[Link to separate ticket ](https://github.com/wrachel/TaxEvaders/issues/8)

**Comment by wrachel** [comment]
Rachel:
Unit 2 frq [frontend](https://github.com/wrachel/TaxEvaders/blob/main/src/main/resources/templates/frqs/rachelfrq2.html) and [model](https://github.com/wrachel/TaxEvaders/blob/main/src/main/java/com/project/frqs/rachel/LightSequence.java) and [controller](https://github.com/wrachel/TaxEvaders/blob/main/src/main/java/com/project/passwordmanager/controllers/controller.java)
About page specifications:

- [ ] [Front end](https://github.com/wrachel/TaxEvaders/blob/main/src/main/resources/templates/frontend/about-rachel.html): contains layout consistent with rest of website, Mask with toggle, links to [FRQ Unit 2 that contains CollegeBoard Notes](https://github.com/wrachel/TaxEvaders/blob/main/src/main/resources/templates/frqs/rachelfrq2.html)
- [ ] [Web API in controller](https://github.com/wrachel/TaxEvaders/blob/main/src/main/java/com/project/passwordmanager/controllers/controller.java): in the controller under GetMapping for /about/rachel. Gets the weather for different cities. [links to commits](https://github.com/wrachel/TaxEvaders/commit/eb5bd4bb57f1569e760d39bb3b24c11eeb05c8fd)

**Comment by wrachel** [comment]
Kevin:

Unit 2 FRQ work: [frontend](https://github.com/wrachel/TaxEvaders/blob/main/src/main/resources/templates/frontend/kevin/unit2.html); [model](https://github.com/wrachel/TaxEvaders/blob/main/src/main/java/com/project/frqs/kevin/LightSequence.java); [controller](https://github.com/wrachel/TaxEvaders/blob/main/src/main/java/com/project/frqs/kevin/LightSequenceController.java)

About page specifications:

**Comment by wrachel** [comment]
Bryant: 
Unit 2 frq [frontend](https://github.com/wrachel/TaxEvaders/blob/main/src/main/resources/templates/frqs/frq2.html) and [model](https://github.com/wrachel/TaxEvaders/blob/main/src/main/java/com/project/frqs/bryant/LightSequence.java) and [controller](https://github.com/wrachel/TaxEvaders/blob/main/src/main/java/com/project/frqs/bryant/controllers/controller.java)
[commit link](https://github.com/wrachel/TaxEvaders/commit/c6d44ac64f2d85861784de017a3e3732ee51c747)

About page specifications:

- [x] [Front end](https://github.com/wrachel/TaxEvaders/blob/main/src/main/resources/templates/frontend/BryantAbout.html): contains layout consistent with rest of website, Mask with toggle is in HTML; commit links: a1ef5dc87686d3d3cf01568ef8f83889c9995e7e, 34e80978e311681ceab870e18cbb04f2362d58e5
- [x] [Web API in controller](https://github.com/wrachel/TaxEvaders/blob/main/src/main/java/com/project/passwordmanager/controllers/controller.java): in the controller under GetMapping for /about/rachel. Gets the weather for different cities. [links to commits](https://github.com/wrachel/TaxEvaders/commit/eb5bd4bb57f1569e760d39bb3b24c11eeb05c8fd)

**Comment by wrachel** [comment]
Harry:
Unit 2 frq [link](https://github.com/wrachel/TaxEvaders/blob/main/src/main/resources/templates/frontend/harryfrq2.html)
commit links: 9e28b8f90c5f65dde3fa073ef5cb6f9d8f5ccdb3 

About page specifications:

- [x] [Front end](https://github.com/wrachel/TaxEvaders/blob/main/src/main/resources/templates/frontend/about-rachel.html): contains layout consistent with rest of website, Mask with toggle, links to [FRQ Unit 2 that contains CollegeBoard Notes](https://github.com/wrachel/TaxEvaders/blob/main/src/main/resources/templates/frqs/rachelfrq2.html)
- [x] [Web API in controller](https://github.com/wrachel/TaxEvaders/blob/main/src/main/java/com/project/passwordmanager/controllers/controller.java): in the controller under GetMapping for /about/rachel. Gets the weather for different cities. [links to commits](https://github.com/wrachel/TaxEvaders/commit/eb5bd4bb57f1569e760d39bb3b24c11eeb05c8fd)

**Comment by wrachel** [comment]
> **Team** README quality, release day policies, Scrum Board to week after break
> 
> * [x ]  1.0
> * [ ]  .75
> * [ ]  .5
> * [ ]  0
>   Justification: [README](https://github.com/wrachel/TaxEvaders#readme) is thorough and up to date. It contains the ideation for our project and is easy for anyone to use, even those who stumble across the project and is not familiar with the class. [Scrum Board](https://github.com/wrachel/TaxEvaders/projects/1) contains all tickets needed to get the team through Week 3 and into Week 4. 
> 
> Team: Deployed Web Site
> 
> * [ x ]  1.0
> * [ ]   .75
> * [ ]  .5
> * [ ]   0
>   Justification: Deployed website is complete and on [taxevaders.pentahex.xyz](taxevaders.pentahex.xyz)
>

**Comment by wiz124** [comment]
Team  
README quality, release day policies, Scrum Board to week after break
☐ 1.0
☐ .75
☐ .5
☐ 0  
   Justification:
Team: Deployed Web Site
☐ 1.0
☐ .75
☐ .5
☐ 0  
   Justification:
Individual  
About Pages on deployed on Site
☐ 1.0
☐ .75
☐ .5
☐ 0  
   Justification:
Page must use a Layout and have special customization (color pallet, background, etc)
☐ 1.0
☐ .75
☐ .5
☐ 0  
   Justification:
Picture with Mask that toggles to Picture of Choice (ie pic without mask). Perhaps ASCII art.
☐ 1.0
☐ .75
☐ .5
☐ 0  
   Justification:
Pull or show data (Web API) with information of interest
☐ 1.0
☐ .75
☐ .5
☐ 0  
   Justification:
Establish link(s) to journal and other key indicators of your work and progress on your home page (remember Tri 1 pop quiz)
☐ 1.0
☐ .75
☐ .5
☐ 0  
   Justification:
Store and Retrieve Data
☐ 1.0
☐ .75
☐ .5
☐ 0  
   Justification:
Unit #2 FRQ deployed
☐ 1.0
☐ .75
☐ .5
☐ 0  
   Justification:

**Comment by wiz124** [comment]
Team  
README quality, release day policies, Scrum Board to week after break

- [ ] ☐ 1.0
- [ ]☐ .75
- [ ]☐ .5
- [ ]☐ 0  
   Justification:
Team: Deployed Web Site
- [ ]☐ 1.0
- [ ]☐ .75
- [ ]☐ .5
- [ ]☐ 0  
   Justification:
Individual  
About Pages on deployed on Site
- [ ]☐ 1.0
- [ ]☐ .75
- [ ]☐ .5
- [ ]☐ 0  
   Justification:
Page must use a Layout and have special customization (color pallet, background, etc)
- [ ]☐ 1.0
- [ ]☐ .75
- [ ]☐ .5
- [ ]☐ 0  
   Justification:
Picture with Mask that toggles to Picture of Choice (ie pic without mask). Perhaps ASCII art.
- [ ]☐ 1.0
- [ ]☐ .75
- [ ]☐ .5
- [ ]☐ 0  
   Justification:
Pull or show data (Web API) with information of interest
- [ ]☐ 1.0
- [ ]☐ .75
- [ ]☐ .5
- [ ]☐ 0  
   Justification:
Establish link(s) to journal and other key indicators of your work and progress on your home page (remember Tri 1 pop quiz)
- [ ]☐ 1.0
- [ ]☐ .75
- [ ]☐ .5
- [ ]☐ 0  
   Justification:
Store and Retrieve Data
- [ ]☐ 1.0
- [ ]☐ .75
- [ ]☐ .5
- [ ]☐ 0  
   Justification:
Unit #2 FRQ deployed
- [ ]☐ 1.0
- [ ]☐ .75
- [ ]☐ .5
- [ ]☐ 0  
   Justification:
