### ISSUE TITLE
Review Ticket Week 3

### ISSUE THREAD

**Issue by wrachel** [wrachel/TaxEvaders#20]
Design Manager tangibles

- [x] [layout](https://github.com/wrachel/TaxEvaders/blob/main/src/main/resources/templates/layout.html)
- [x] [login page](https://taxevasion.pentahex.xyz/signin) 
- [x] [password tester ](https://taxevasion.pentahex.xyz/passtester)
- [x] [password manager](https://taxevasion.pentahex.xyz/passmanager)

Technical Officer
- [x] Database integration: 94e63685cacc613ad305e037b7225e910a2cd444, 521e5dc16a1ce6560345eb21a5fa92fbc957b406, e00dfbd743e32751e87b46382bc91a0ac8b07122, 3fe4e2eac3aef9e907336498858390c54621c77c
- [x] CRUD page runtime: https://github.com/wrachel/TaxEvaders/blob/main/src/main/resources/templates/frontend/passmanager.html
- [x] Javascript fetch: https://github.com/wrachel/TaxEvaders/blob/main/src/main/resources/templates/frontend/passmanager.html#L88-L127
- [x] control: https://github.com/wrachel/TaxEvaders/blob/main/src/main/java/com/project/passwordmanager/controllers/controller.java#L377-L385
- [x] Model SQL: https://github.com/wrachel/TaxEvaders/blob/main/src/main/java/com/project/passwordmanager/sql_helper.java
- [x] Model JPA: None

Deployment Manager
- [x] deployed website: taxevasion.pentahex.xyz
- [x] [update procedure](https://github.com/wrachel/TaxEvaders/wiki/Deployment)
- [x] [nginx config](https://github.com/wrachel/TaxEvaders/wiki/Nginx-example-config)
- [x] [service config](https://github.com/wrachel/TaxEvaders/wiki/service-config-file-example)

Scrum Master tangibles
- [x] Check scrum board for updates on completed issues & tickets
- [x] GitHub README timebox
- [x] Github Scrum Board 

Github Admin
- [x] Commits by Bryant for Database implementation: 94e63685cacc613ad305e037b7225e910a2cd444, 521e5dc16a1ce6560345eb21a5fa92fbc957b406, e00dfbd743e32751e87b46382bc91a0ac8b07122, 3fe4e2eac3aef9e907336498858390c54621c77c
- [x] Commits by Kevin for Frontend 7efa52e28fbcc22dd2ec2e32585ff3376d15ac49, d3df43ebfd6948ac92a72fabd82aa590ca6d08c0, c134d58b1de2de87302fd76d5a6d6b8e9431b5c5
- [x] Commits by Rachel dealing with frq3: 3b6b31e93e1a405b4947aff9c6393943d19cf4dd f82b4ae3d00dac469c7af80ba08c0ec1a110d76b, debugging API: 33775627db3129e0160d3ed94f951c0e87f632b9, 
- [x] Commits by Harry: cf9298da89513add813aedf7eec2ae9763cc4619, cb75da8270b08a09388979c2fd8695fecfe25fe3, 0e9c08ea6d16332b38c51884a35923aa7206866d
- [x] [contributing.md](https://github.com/wrachel/TaxEvaders/blob/main/contributing.md) contains policies on commits and branching

**Comment by wrachel** [comment]
Kevin FRQ2: [link to Java](https://github.com/wrachel/TaxEvaders/blob/main/src/main/java/com/project/passwordmanager/controllers/kevin/LightSequence.java) 
Bryant FRQ2: [link to Java](https://github.com/wrachel/TaxEvaders/blob/main/src/main/java/com/project/frqs/bryant/LightSequence.java)
Rachel FRQ2: [link to Java](https://github.com/wrachel/TaxEvaders/blob/main/src/main/java/com/project/frqs/rachel/LightSequence.java)
Harry FRQ2: [link to Java](https://github.com/wrachel/TaxEvaders/blob/main/src/main/java/com/project/frqs/harry/lightsequence.java)

Bryant FRQ3: [link to Java](https://github.com/wrachel/TaxEvaders/blob/main/src/main/resources/templates/frqs/frq3.html)
Kevin FRQ3: [Link to Java](https://github.com/wrachel/TaxEvaders/blob/main/src/main/java/com/project/passwordmanager/controllers/kevin/frq3.java)
Rachel FRQ3: [Link to Java](https://github.com/wrachel/TaxEvaders/blob/main/src/main/java/com/project/frqs/rachel/rachelfrq3.java)
Harry FRQ3: [Link to Java](https://github.com/wrachel/TaxEvaders/blob/main/src/main/resources/templates/frqs/harryfrq3.html)

**Comment by wrachel** [comment]
Scoring:
Individual Scores
Kevin: 7/7, 5/5 on team, 2/2 on individual
Bryant: 7/7, 5/5 on team, 2/2 on individual
Rachel: 7/7, 5/5 on team, 2/2 on individual
Harry: 7/7, 5/5 on team, 2/2 on individual

**Comment by jm1021** [comment]
All your scores hold.  Thanks for you work.  Comments

Could night find FRQ3 for Rachel.   Light Seq for Kevin always fails for me.  All the others look good.
