### ISSUE TITLE
FRQ Review - Rachel & Sarah

### ISSUE THREAD

**Issue by wrachel** [wrachel/TaxEvaders#30]

**Comment by wrachel** [comment]
Reflection:

**Comment by sarahwxie** [comment]
<html>
<body>
<p dir="auto" style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Rachel's Score(s)<br style="box-sizing: border-box;">Graded by Sarah</p>

Requirement | Evaluation
-- | --
Each individual has GitHub Page, Wiki, or deployed Web Page that Highlights talking points and learnings from each FRQ | On Rachel's about page, she has all of her FRQs linked to an external site which includes source code, a description and reflection on the FRQs, as well as the running FRQ if its one of the FRQs that take input. Some are deployed on PBL, while others are run on Repl.it
Each Individual has their own set of FRQs running under one page or menu (ie Deployed Java/Spring or Replit) | Yes, all of Rachel's FRQs are available to view from her "About" page. Every FRQ has code and a reflection available from this one spot, which makes it very convenient to grade. 
Each Individual has GitHub of source for every FRQ that is integrated with Deployed Java/Spring or Replit | On all her FRQ pages, she has a link to her Java source code, so her code is extremely easy to find and the site is evidently built very thoughtfully. 
At least 2 FRQs with input and output (10%) | Rachels FRQ4 Question 1 and Question 2, as well as FRQ Unit 5 Question 1 & 2, as well as FRQ3 are all deployed on the site with input and output, and are very well done. 

<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Overall comments:<br style="box-sizing: border-box;">The FRQ pages are very thoroughly made, and well organized. </p><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px !important; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Scoring:<br style="box-sizing: border-box;">I'm going to score her a 9.8/10. All of the FRQs, reflections, and source code were very organized and viewable. The video was also very helpful in helping me grade. Some improvements that could be made are to make a more appealing UI on the FRQ pages, but overall, Rachel has everything required and it is done extremely well.  </p>
</body>
</html>
