### ISSUE TITLE
FRQ Review - Kevin

### ISSUE THREAD

**Issue by kevin-dough** [wrachel/TaxEvaders#31]
# Kevin's FRQ Review
> Crossover Partner: Kyle Myint

## Comparison
> FRQs for Comparison: 8, 9, 10

### FRQ 8
[FRQ 8 Code](https://github.com/wrachel/TaxEvaders/blob/main/src/main/java/com/project/passwordmanager/controllers/kevin/ExperimentalFarm.java)

- in the ExperimentalFarm constructor, I cloned the array `p` whereas Kyle did `this.farmPlots=p;`
- we both use nested loops in the `getHighestYield` method
- our `sameCrop` method is pretty much the same

### FRQ 9
[FRQ 9 Code PictureBook](https://github.com/wrachel/TaxEvaders/blob/main/src/main/java/com/project/passwordmanager/controllers/kevin/PictureBook.java)

[FRQ 9 Code BookListing](https://github.com/wrachel/TaxEvaders/blob/main/src/main/java/com/project/passwordmanager/controllers/kevin/BookListing.java)

[FRQ 9 Code Animal](https://github.com/wrachel/TaxEvaders/blob/main/src/main/java/com/project/passwordmanager/controllers/kevin/Animal.java)

[FRQ 9 Code Herbivore](https://github.com/wrachel/TaxEvaders/blob/main/src/main/java/com/project/passwordmanager/controllers/kevin/Herbivore.java)

[FRQ 9 Code Elephant](https://github.com/wrachel/TaxEvaders/blob/main/src/main/java/com/project/passwordmanager/controllers/kevin/Elephant.java)

- our `printBookInfo()` in `PictureBook` methods are the same (mine was edited a bit in order to display things on the website
- we also have similar overall code for `BookListing` class

### FRQ 10
[FRQ 10 Code](https://github.com/wrachel/TaxEvaders/blob/main/src/main/java/com/project/passwordmanager/controllers/kevin/NumberSystem.java)

- my code is more concise than Kyle's code
- he has a condition for if b=0, which is better since it will avoid an error

## FRQ 2

- [x] on website
- [x] input/output

## FRQ 3

- [x] on website
- [x] input/output

## FRQ 4

- [x] on website
- [x] input/output

## FRQ 5

- [x] on website
- [x] input/output

## FRQ 6

- [x] on website
- [x] input/output

## FRQ 7

- [x] on website
- [x] input/output

## FRQ 8

- [x] on website
- [x] input/output

## FRQ 9

- [x] on website
- [x] input/output

## FRQ 10

- [x] on website
- [x] input/output

**Comment by kylem314** [comment]
## Score: 10/10

Every FRQ is on website and has user input 
Potential extra credit?  Extra information is displayed on the website beyond the output - very clean and well put together overall
