### ISSUE TITLE
Week 1 - Project Approval Review Ticket

### ISSUE THREAD

**Issue by kevin-dough** [wrachel/TaxEvaders#9]
- [x] Design - Wiki Theme, Brain Write & Wire Frame: [Wiki page Brain Write](https://github.com/wrachel/TaxEvaders/wiki/Brain-Write) ; [Wiki page Wireframe](https://github.com/wrachel/TaxEvaders/wiki/Wire-Frame)
- [x] Technicals - 10  to 12 key ideas: [Wiki page](https://github.com/wrachel/TaxEvaders/wiki/10-to-12-Key-Ideas)
- [x] Github - On Wiki containing Management Plan, forking, branching, pull request, etc: [contributing.md](https://github.com/wrachel/TaxEvaders/blob/main/contributing.md)
- [x] Deployment - On Wiki containing Hardware, frequency, etc: [Wiki page](https://github.com/wrachel/TaxEvaders/wiki/Deployment)
- [x] Scrum Board - Assignments and Backlog: [Scrum Board](https://github.com/wrachel/TaxEvaders/projects/1) ; [Wiki](https://github.com/wrachel/TaxEvaders/wiki/Scrum-Team-Management-Plan:-BOF-Scrum-Masters-Questions)

**Comment by kylem314** [comment]
Github - On Wiki containing Management Plan, forking, branching, pull request, etc
The contributing.md file clearly outlines the guidelines for contributing to the project in order to avoid issues - 1/1

Scrum Board - Assignments and Backlog
Everyone has assignments on the scrum board to contribute to the project, including planned tasks to complete in the future 1/1

**Comment by 1855387** [comment]
Design -  The Wiki theme is very organized and well done. The brain write on the wiki page that was linked looked good, you guys listed all of your ideas pretty well. The Wireframe's sketches were also uhhh pretty well done. I can see where the project is going on a frontend aspect. Good job. 

1/1

**Comment by elw55555** [comment]
Deployment Guide - hardware, frequency, etc:
The Deployment Guide is detailed and I like how you set a deadline for all members to leave sufficient time for deployment. The AWS guide seems straightforward to follow and successfully deploy.

**Comment by yajatyadav** [comment]
Technicals- There is a good variety of creative ideas and they are formatted properly on the wiki and scrum board too. I especially liked the hashing algorithm feature. I would recommend adding a search bar to search through the database. 1/1

**Comment by jm1021** [comment]
axEvaders - Rachel W. 4.7
* Password storage database 1.0/1.0
* Discussed CRUD operation, UI is minimal .9/1
* Working on main except for longer tasks .9/1
* Deployment…. Little bit more explicit 
* Scrum Board Friday/Monday 1/1

**Comment by jm1021** [comment]
Score raised to 4.8 based off of peer review
